name: 'pytest-cov XML commenter'
description: 'Parse pytest-cov XML output and comment to pull request'
inputs:
  file:
    description: 'Filename to parse'
    required: true
    default: 'coverage.xml'
  token:
    description: 'GITHUB_TOKEN'
    required: true
    default: ${{ github.token }}
runs:
  using: 'node12'
  main: 'dist/index.js'
